modLoader = "javafml"
loaderVersion = "[40,)" # This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "All Rights Reserved"
issueTrackerURL="https://github.com/Ultreon/small-utilities/issues"

[[mods]]
modId = "smallutils"
version = "${version}"
displayName = "Small Utilities"
#updateJSONURL="http://myurl.me/"
displayURL="https://github.com/Ultreon/small-utilities"
logoFile="small-utilities.png"
credits="Qboi"
authors = "Ultreon Team"
description = '''
Small utilities to make minecraft a little bit more realistic

§6Credits:
    §e***§7 Laptop V2 by FishyBusiness is licensed under Creative Commons Attribution§e ***
    §8License:§7 http://creativecommons.org/licenses/by/4.0/
    §8Download:§7 https://sketchfab.com/3d-models/laptop-v2-10b153c036d54f6ea03e08e6f81e33f6
    §8User:§7 https://sketchfab.com/FishyBusiness

    §e***§7 Trash Can [Minecraft] by sedona1029 is licensed under Creative Commons Attribution§e ***
    §8License:§7 http://creativecommons.org/licenses/by/4.0/
    §8Download:§7 https://sketchfab.com/3d-models/trash-can-minecraft-831dd489b8044ba8bb77f0ca253dcfde
    §8User:§7 https://sketchfab.com/sedona1029
'''

[[dependencies.smallutils]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.smallutils]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
